# -*- coding: utf-8 -*-
"""Regre_phyton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGRIFG0-bKvfwjZjMX83ZSW-X5TSFBBj
"""

import numpy as np
import time

# Cronometro
start = time.time()

# Datos de ejemplo
X = np.array([1, 2, 3, 4, 5], dtype=float)
y = np.array([2, 4, 6, 8, 10], dtype=float)

# Inicialización de parámetros
w = 0.0  # pendiente
b = 0.0  # intercepto

# Hiperparametros
learning_rate = 0.01
epochs = 1000

m = len(X)

for epoch in range(epochs):
    # Prediccion
    y_pred = w * X + b

    # Error
    error = y_pred - y

    # Gradientes
    dw = (2/m) * np.dot(error, X)
    db = (2/m) * np.sum(error)

    # Actualización
    w -= learning_rate * dw
    b -= learning_rate * db

    if (epoch + 1) % 200 == 0:
        mse = np.mean(error ** 2)
        print(f"Epoch {epoch+1}, MSE: {mse:.4f}, w: {w:.4f}, b: {b:.4f}")

end = time.time()
print("\nModelo entrenado:")
print(f"w ≈ {w:.4f}, b ≈ {b:.4f}")
print("Tiempo Python:", end - start, "segundos")

# Prueba
x_nuevo = 7
print(f"Para x = {x_nuevo}, y_pred ≈ {w*x_nuevo + b:.4f}")